# Pandas Lesson Plan 
## 11/26/2018
- ideas
    - import this
    - byod
        - troubleshoot specific projects
    - setup mybinder instance for class
        - how to save that?
    - icon relationship
        - excel, numpy, sklearn, geopandas, R, stackoverflow and documentation
- exercises
- specifics to highlight:
    - import data
    - save data
    - save figure
## Resources
- [Working through Chronic Disease Dataset](https://healthcare.ai/we-heart-pandas/)
- [CDC Dataset](https://healthdata.gov/dataset/us-chronic-disease-indicators-cdi)
- [CDC Dictionary for Dataset](https://chronicdata.cdc.gov/Chronic-Disease-Indicators/U-S-Chronic-Disease-Indicators-CDI-/g4ie-h725)

In [ ]:
## outline
- quick overview how things work
    - python syntax
        - object
        - functions
        - attributes
        - comments
    - jupyter notebooks
    - what is pandas
    - objects and attributes
- importing data
    - read_csv
    - read_excel
- cleaning data
    - .head()
    - .shape
    - .columns
    - select by value
    - value_counts()
    - unique()
    - nunique()
- examine data
    - info()
    - describe()
    - plot()
        - paired bar (male and female)
        - location by states
- exercise: extend this to a different question
    - value of recycling code

In [2]:
import pandas as pd

In [11]:
# import the data we'll be using
# note that the path to the data is relative to the Jupyter notebook location

df = pd.read_csv('data/diabetes.csv')

/Users/chambersmj/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (8,11,19,20,21,22,24,31,32,33,34) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [12]:
df

,Unnamed: 0,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,Question,Response,DataValueUnit,...,LocationID,TopicID,QuestionID,DataValueTypeID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2,StratificationCategoryID3,StratificationID3
0,14270,2016,2016,HI,Hawaii,BRFSS,Diabetes,Diabetes prevalence among women aged 18-44 years,NaN,%,...,15,DIA,DIA2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
1,14313,2016,2016,ID,Idaho,BRFSS,Diabetes,Diabetes prevalence among women aged 18-44 years,NaN,%,...,16,DIA,DIA2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
2,14496,2016,2016,IL,Illinois,BRFSS,Diabetes,Diabetes prevalence among women aged 18-44 years,NaN,%,...,17,DIA,DIA2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
3,14742,2016,2016,MN,Minnesota,BRFSS,Diabetes,Diabetes prevalence among women aged 18-44 years,NaN,%,...,27,DIA,DIA2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
4,15133,2016,2016,GU,Guam,BRFSS,Diabetes,Diabetes prevalence among women aged 18-44 years,NaN,%,...,66,DIA,DIA2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
5,15326,2016,2016,IN,Indiana,BRFSS,Diabetes,Diabetes prevalence among women aged 18-44 years,NaN,%,...,18,DIA,DIA2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
6,15792,2016,2016,IA,Iowa,BRFSS,Diabetes,Diabetes prevalence among women aged 18-44 years,NaN,%,...,19,DIA,DIA2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
7,15821,2016,2016,PR,Puerto Rico,BRFSS,Diabetes,Diabetes prevalence among women aged 18-44 years,NaN,%,...,72,DIA,DIA2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
8,16097,2016,2016,KS,Kansas,BRFSS,Diabetes,Diabetes prevalence among women aged 18-44 years,NaN,%,...,20,DIA,DIA2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
9,16178,2016,2016,GU,Guam,BRFSS,Diabetes,Prevalence of depressive disorders among adult...,NaN,%,...,66,DIA,DIA11_3,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
10,16435,2016,2016,DC,District of Columbia,BRFSS,Diabetes,Prevalence of diagnosed diabetes among adults ...,NaN,%,...,11,DIA,DIA2_1,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
11,16510,2016,2016,KY,Kentucky,BRFSS,Diabetes,Diabetes prevalence among women aged 18-44 years,NaN,%,...,21,DIA,DIA2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
12,16529,2016,2016,LA,Louisiana,BRFSS,Diabetes,Diabetes prevalence among women aged 18-44 years,NaN,%,...,22,DIA,DIA2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
13,16673,2016,2016,ME,Maine,BRFSS,Diabetes,Diabetes prevalence among women aged 18-44 years,NaN,%,...,23,DIA,DIA2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
14,16715,2016,2016,MD,Maryland,BRFSS,Diabetes,Diabetes prevalence among women aged 18-44 years,NaN,%,...,24,DIA,DIA2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
15,17073,2016,2016,VA,Virginia,BRFSS,Diabetes,Diabetes prevalence among women aged 18-44 years,NaN,%,...,51,DIA,DIA2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
16,17160,2016,2016,FL,Florida,BRFSS,Diabetes,Prevalence of diagnosed diabetes among adults ...,NaN,%,...,12,DIA,DIA2_1,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
17,17196,2016,2016,GA,Georgia,BRFSS,Diabetes,Prevalence of diagnosed diabetes among adults ...,NaN,%,...,13,DIA,DIA2_1,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
18,17336,2016,2016,HI,Hawaii,BRFSS,Diabetes,Prevalence of diagnosed diabetes among adults ...,NaN,%,...,15,DIA,DIA2_1,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
19,17425,2016,2016,WA,Washington,BRFSS,Diabetes,Diabetes prevalence among women aged 18-44 years,NaN,%,...,53,DIA,DIA2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
20,17829,2016,2016,AK,Alaska,BRFSS,Diabetes,Adults with diagnosed diabetes aged >= 18 year...,NaN,%,...,2,DIA,DIA10_0,AGEADJPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
21,18040,2016,2016,AL,Alabama,BRFSS,Diabetes,Adults with diagnosed diabetes aged >= 18 year...,NaN,%,...,1,DIA,DIA10_0,AGEADJPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
22,18057,2016,2016,LA,Louisiana,BRFSS,Diabetes,Adults with diagnosed diabetes aged >= 18 year...,NaN,%,...,22,DIA,DIA10_0,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
23,18177,2016,2016,ME,Maine,BRFSS,Diabetes,Adults with diagnosed diabetes aged >= 18 year...,NaN,%,...,23,DIA,DIA10_0,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
24,18194,2016,2016,ID,Idaho,BRFSS,Diabetes,Prevalence of diagnosed diabetes among adults ...,NaN,%,...,16,DIA,DIA2_1,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
25,18279,2016,2016,MD,Maryland,BRFSS,Diabetes,Adults with diagnosed diabetes aged >= 18 year...,NaN,%,...,24,DIA,DIA10_0,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
26,18316,2016,2016,IL,Illinois,BRFSS,Diabetes,Prevalence of diagnosed diabetes among adults ...,NaN,%,...,17,DIA,DIA2_1,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
27,18336,2016,2016,IN,Indiana,BRFSS,Diabetes,Prevalence of diagnosed diabetes among adults ...,NaN,%,...,18,DIA,DIA2_1,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
28,18568,2016,2016,MA,Massachusetts,BRFSS,Diabetes,Adults with diagnosed diabetes aged >= 18 year...,NaN,%,...,25,DIA,DIA10_0,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
29,18587,2016,2016,IA,Iowa,BRFSS,Diabetes,Prevalence of diagnosed diabetes among adults ...,NaN,%,...,19,DIA,DIA2_1,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79601,519064,2014,2014,US,United States,BRFSS,Diabetes,Dilated eye examination among adults aged >= 1...,NaN,%,...,59,DIA,DIA7_0,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
79602,519065,2016,2016,US,United States,BRFSS,Diabetes,Dilated eye examination among adults aged >= 1...,NaN,%,...,59,DIA,DIA7_0,AGEADJPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
79603,519066,2016,2016,US,United States,BRFSS,Diabetes,Dilated eye examination among adults aged >= 1...,NaN,%,...,59,DIA,DIA7_0,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
79604,519067,2013,2013,GU,Guam,State Inpatient Data,Diabetes,Hospitalization with diabetes as a listed diag...,NaN,NaN,...,66,DIA,DIA9_0,NMBR,OVERALL,OVR,NaN,NaN,NaN,NaN
79605,519068,2013,2013,GU,Guam,State Inpatient Data,Diabetes,Hospitalization with diabetes as a listed diag...,NaN,"cases per 10,000",...,66,DIA,DIA9_0,CRDRATE,OVERALL,OVR,NaN,NaN,NaN,NaN
79606,519069,2013,2013,GU,Guam,State Inpatient Data,Diabetes,Hospitalization with diabetes as a listed diag...,NaN,"cases per 10,000",...,66,DIA,DIA9_0,AGEADJRATE,OVERALL,OVR,NaN,NaN,NaN,NaN
79607,519070,2013,2013,PR,Puerto Rico,State Inpatient Data,Diabetes,Hospitalization with diabetes as a listed diag...,NaN,NaN,...,72,DIA,DIA9_0,NMBR,OVERALL,OVR,NaN,NaN,NaN,NaN
79608,519071,2013,2013,PR,Puerto Rico,State Inpatient Data,Diabetes,Hospitalization with diabetes as a listed diag...,NaN,"cases per 10,000",...,72,DIA,DIA9_0,CRDRATE,OVERALL,OVR,NaN,NaN,NaN,NaN
79609,519072,2013,2013,PR,Puerto Rico,State Inpatient Data,Diabetes,Hospitalization with diabetes as a listed diag...,NaN,"cases per 10,000",...,72,DIA,DIA9_0,AGEADJRATE,OVERALL,OVR,NaN,NaN,NaN,NaN
79610,519073,2013,2013,VI,Virgin Islands,State Inpatient Data,Diabetes,Hospitalization with diabetes as a listed diag...,NaN,NaN,...,78,DIA,DIA9_0,NMBR,OVERALL,OVR,NaN,NaN,NaN,NaN
79611,519074,2013,2013,VI,Virgin Islands,State Inpatient Data,Diabetes,Hospitalization with diabetes as a listed diag...,NaN,"cases per 10,000",...,78,DIA,DIA9_0,CRDRATE,OVERALL,OVR,NaN,NaN,NaN,NaN
79612,519075,2013,2013,VI,Virgin Islands,State Inpatient Data,Diabetes,Hospitalization with diabetes as a listed diag...,NaN,"cases per 10,000",...,78,DIA,DIA9_0,AGEADJRATE,OVERALL,OVR,NaN,NaN,NaN,NaN
79613,519076,2010,2010,GU,Guam,State Inpatient Data,Diabetes,Hospitalization with diabetes as a listed diag...,NaN,NaN,...,66,DIA,DIA9_0,NMBR,OVERALL,OVR,NaN,NaN,NaN,NaN
79614,519077,2010,2010,GU,Guam,State Inpatient Data,Diabetes,Hospitalization with diabetes as a listed diag...,NaN,"cases per 10,000",...,66,DIA,DIA9_0,CRDRATE,OVERALL,OVR,NaN,NaN,NaN,NaN
79615,519078,2010,2010,GU,Guam,State Inpatient Data,Diabetes,Hospitalization with diabetes as a listed diag...,NaN,"cases per 10,000",...,66,DIA,DIA9_0,AGEADJRATE,OVERALL,OVR,NaN,NaN,NaN,NaN
79616,519079,2010,2010,PR,Puerto Rico,State Inpatient Data,Diabetes,Hospitalization with diabetes as a listed diag...,NaN,NaN,...,72,DIA,DIA9_0,NMBR,OVERALL,OVR,NaN,NaN,NaN,NaN
79617,519080,2010,2010,PR,Puerto Rico,State Inpatient Data,Diabetes,Hospitalization with diabetes as a listed diag...,NaN,"cases per 10,000",...,72,DIA,DIA9_0,CRDRATE,OVERALL,OVR,NaN,NaN,NaN,NaN
79618,519081,2010,2010,PR,Puerto Rico,State Inpatient Data,Diabetes,Hospitalization with diabetes as a listed diag...,NaN,"cases per 10,000",...,72,DIA,DIA9_0,AGEADJRATE,OVERALL,OVR,NaN,NaN,NaN,NaN
79619,519082,2010,2010,VI,Virgin Islands,State Inpatient Data,Diabetes,Hospitalization with diabetes as a listed diag...,NaN,NaN,...,78,DIA,DIA9_0,NMBR,OVERALL,OVR,NaN,NaN,NaN,NaN
79620,519083,2010,2010,VI,Virgin Islands,State Inpatient Data,Diabetes,Hospitalization with diabetes as a listed diag...,NaN,"cases per 10,000",...,78,DIA,DIA9_0,CRDRATE,OVERALL,OVR,NaN,NaN,NaN,NaN
79621,519084,2010,2010,VI,Virgin Islands,State Inpatient Data,Diabetes,Hospitalization with diabetes as a listed diag...,NaN,"cases per 10,000",...,78,DIA,DIA9_0,AGEADJRATE,OVERALL,OVR,NaN,NaN,NaN,NaN
79622,519085,2014,2014,US,United States,State Inpatient Data,Diabetes,Hospitalization with diabetes as a listed diag...,NaN,NaN,...,59,DIA,DIA9_0,NMBR,OVERALL,OVR,NaN,NaN,NaN,NaN
79623,519086,2014,2014,US,United States,State Inpatient Data,Diabetes,Hospitalization with diabetes as a listed diag...,NaN,"cases per 10,000",...,59,DIA,DIA9_0,CRDRATE,OVERALL,OVR,NaN,NaN,NaN,NaN
79624,519087,2014,2014,US,United States,State Inpatient Data,Diabetes,Hospitalization with diabetes as a listed diag...,NaN,"cases per 10,000",...,59,DIA,DIA9_0,AGEADJRATE,OVERALL,OVR,NaN,NaN,NaN,NaN
79625,519088,2013,2013,US,United States,State Inpatient Data,Diabetes,Hospitalization with diabetes as a listed diag...,NaN,NaN,...,59,DIA,DIA9_0,NMBR,OVERALL,OVR,NaN,NaN,NaN,NaN
79626,519089,2013,2013,US,United States,State Inpatient Data,Diabetes,Hospitalization with diabetes as a listed diag...,NaN,"cases per 10,000",...,59,DIA,DIA9_0,CRDRATE,OVERALL,OVR,NaN,NaN,NaN,NaN
79627,519090,2013,2013,US,United States,State Inpatient Data,Diabetes,Hospitalization with diabetes as a listed diag...,NaN,"cases per 10,000",...,59,DIA,DIA9_0,AGEADJRATE,OVERALL,OVR,NaN,NaN,NaN,NaN
79628,519091,2010,2010,US,United States,State Inpatient Data,Diabetes,Hospitalization with diabetes as a listed diag...,NaN,NaN,...,59,DIA,DIA9_0,NMBR,OVERALL,OVR,NaN,NaN,NaN,NaN
79629,519092,2010,2010,US,United States,State Inpatient Data,Diabetes,Hospitalization with diabetes as a listed diag...,NaN,"cases per 10,000",...,59,DIA,DIA9_0,CRDRATE,OVERALL,OVR,NaN,NaN,NaN,NaN
79630,519093,2010,2010,US,United States,State Inpatient Data,Diabetes,Hospitalization with diabetes as a listed diag...,NaN,"cases per 10,000",...,59,DIA,DIA9_0,AGEADJRATE,OVERALL,OVR,NaN,NaN,NaN,NaN

In [13]:
df['Question'].unique().tolist()

['Diabetes prevalence among women aged 18-44 years',
 'Prevalence of depressive disorders among adults aged >= 18 years with diagnosed diabetes',
 'Prevalence of diagnosed diabetes among adults aged >= 18 years',
 'Adults with diagnosed diabetes aged >= 18 years who have taken a diabetes self-management course',
 'Influenza vaccination among noninstitutionalized adults aged 18-64 years with diagnosed diabetes',
 'Influenza vaccination among noninstitutionalized adults aged >= 65 years with diagnosed diabetes',
 'Pneumococcal vaccination among noninstitutionalized adults aged 18-64 years with diagnosed diabetes',
 'Pneumococcal vaccination among noninstitutionalized adults aged >= 65 years with diagnosed diabetes',
 'Foot examination among adults aged >= 18 years with diagnosed diabetes',
 'Glycosylated hemoglobin measurement among adults aged >= 18 years with diagnosed diabetes',
 'Dilated eye examination among adults aged >= 18 years with diagnosed diabetes',
 'Visits to dentist or dental clinic among adults aged >= 18 years with diagnosed diabetes',
 'Prevalence of high cholesterol among adults aged >= 18 years with diagnosed diabetes',
 'Prevalence of high blood pressure among adults aged >= 18 years with diagnosed diabetes',
 'Amputation of a lower extremity attributable to diabetes',
 'Hospitalization with diabetes as a listed diagnosis',
 'Mortality due to diabetes reported as any listed cause of death',
 'Mortality with diabetic ketoacidosis reported as any listed cause of death',
 'Prevalence of gestational diabetes',
 'Prevalence of pre-pregnancy diabetes']

In [ ]:
# so what can we do with this "df" data object that we just created?

df. # place cursor after "." and hit "tab" to view options

In [86]:
# what do all these things do?

 # use "?" after any attribute or function to view the documentation?
df.head?

In [69]:
# checak out what it looks like using the ".head()" function
df.head()

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,Question,Response,DataValueUnit,DataValueType,...,LocationID,TopicID,QuestionID,DataValueTypeID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2,StratificationCategoryID3,StratificationID3
0,2016,2016,US,United States,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,59,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
1,2016,2016,AL,Alabama,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,1,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
2,2016,2016,AK,Alaska,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,2,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
3,2016,2016,AZ,Arizona,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,4,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
4,2016,2016,AR,Arkansas,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,5,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN

In [6]:
df.columns.tolist()

['YearStart',
 'YearEnd',
 'LocationAbbr',
 'LocationDesc',
 'DataSource',
 'Topic',
 'Question',
 'Response',
 'DataValueUnit',
 'DataValueType',
 'DataValue',
 'DataValueAlt',
 'DataValueFootnoteSymbol',
 'DatavalueFootnote',
 'LowConfidenceLimit',
 'HighConfidenceLimit',
 'StratificationCategory1',
 'Stratification1',
 'StratificationCategory2',
 'Stratification2',
 'StratificationCategory3',
 'Stratification3',
 'GeoLocation',
 'ResponseID',
 'LocationID',
 'TopicID',
 'QuestionID',
 'DataValueTypeID',
 'StratificationCategoryID1',
 'StratificationID1',
 'StratificationCategoryID2',
 'StratificationID2',
 'StratificationCategoryID3',
 'StratificationID3']

In [7]:
df.head()

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,Question,Response,DataValueUnit,DataValueType,...,LocationID,TopicID,QuestionID,DataValueTypeID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2,StratificationCategoryID3,StratificationID3
0,2016,2016,US,United States,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,59,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
1,2016,2016,AL,Alabama,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,1,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
2,2016,2016,AK,Alaska,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,2,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
3,2016,2016,AZ,Arizona,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,4,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
4,2016,2016,AR,Arkansas,BRFSS,Alcohol,Binge drinking prevalence among adults aged >=...,NaN,%,Crude Prevalence,...,5,ALC,ALC2_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN

In [20]:
df['Topic'].unique()

array(['Alcohol', 'Arthritis', 'Asthma', 'Cancer', 'Diabetes',
       'Mental Health', 'Chronic Obstructive Pulmonary Disease',
       'Oral Health', 'Cardiovascular Disease', 'Immunization',
       'Chronic Kidney Disease',
       'Nutrition, Physical Activity, and Weight Status', 'Older Adults',
       'Tobacco', 'Overarching Conditions', 'Reproductive Health',
       'Disability'], dtype=object)

In [29]:
pd.DataFrame(df.groupby('Topic')['Question'].value_counts())

                                                                           Question
Topic                  Question
Alcohol                Chronic liver disease mortality                         6135
                       Binge drinking frequency among adults aged >= 1...      5220
                       Binge drinking intensity among adults aged >= 1...      5220
                       Binge drinking prevalence among adults aged >= ...      5220
                       Heavy drinking among adults aged >= 18 years            5220
                       Binge drinking prevalence among women aged 18-4...      1950
                       Heavy drinking among women aged 18-44 years             1950
                       Alcohol use among youth                                  110
                       Amount of alcohol excise tax by beverage type (...       110
                       Amount of alcohol excise tax by beverage type (...       110
                       Amount of alcohol excise tax by beverage type (...       110
                       Binge drinking prevalence among youth                    110
                       Commercial host (dram shop) liability laws               110
                       Local authority to regulate alcohol outlet density       110
                       Per capita alcohol consumption among persons ag...       110
                       Alcohol use before pregnancy                              55
Arthritis              Arthritis among adults aged >= 18 years who are...      5225
                       Arthritis among adults aged >= 18 years                 5220
                       Arthritis among adults aged >= 18 years who hav...      5220
                       Arthritis among adults aged >= 18 years who hav...      5220
                       Fair or poor health among adults aged >= 18 yea...      5220
                       Physical inactivity among adults aged >= 18 yea...      5220
                       Activity limitation due to arthritis among adul...      2610
                       Adults aged >= 18 years with arthritis who have...      2610
                       Severe joint pain due to arthritis among adults...      2610
                       Work limitation due to arthritis among adults a...      2610
Asthma                 Asthma mortality rate                                   6135
                       Current asthma prevalence among adults aged >= ...      5220
                       Influenza vaccination among noninstitutionalize...      5220
                       Influenza vaccination among noninstitutionalize...      5220
...                                                                             ...
Overarching Conditions Prevalence of sufficient sleep among adults age...      3480
                       Poverty                                                 2968
                       Current health care coverage among women aged 1...      1950
                       Self-rated health status among women aged 18-44...      1950
                       High school completion among adults aged 18-24 ...      1155
                       Gini Index of income inequality                          318
                       High school completion among women aged 18-44 y...       312
                       Health insurance coverage before pregnancy                55
                       Poverty among women aged 18-44 years                      55
                       Life expectancy at age 65 years                           52
                       Life expectancy at birth                                  52
Reproductive Health    Timeliness of routine health care checkup among...      1950
                       Folic acid supplementation                                55
                       Postpartum checkup                                        55
Tobacco                Current smokeless tobacco use among adults aged...      5220
                       Current smoking among adults aged >= 18 years           5220
                       Pneumococcal vaccination among noninstitutional...      5220
                       Pneumococcal vaccination among noninstitutional...      5220
                       Quit attempts in the past year among current sm...      5220
                       Current cigarette smoking among women aged 18-4...      1950
                       Secondary schools that have a comprehensive tob...       165
                       Amount of tobacco product excise tax                     162
                       States that allow stronger local tobacco contro...       162
                       States with strong polices that require retail ...       162
                       Current cigarette smoking among youth                    110
                       Current smokeless tobacco use among youth                110
                       Percent tobacco revenue to fund at CDC recommen...       110
                       Proportion of the population protected by a com...       110
                       Sale of cigarette packs                                  110
                       Cigarette smoking before pregnancy                        55

[203 rows x 1 columns]

In [23]:
df[df['Topic'] == 'Diabetes']['Question'].unique().tolist()

['Diabetes prevalence among women aged 18-44 years',
 'Prevalence of depressive disorders among adults aged >= 18 years with diagnosed diabetes',
 'Prevalence of diagnosed diabetes among adults aged >= 18 years',
 'Adults with diagnosed diabetes aged >= 18 years who have taken a diabetes self-management course',
 'Influenza vaccination among noninstitutionalized adults aged 18-64 years with diagnosed diabetes',
 'Influenza vaccination among noninstitutionalized adults aged >= 65 years with diagnosed diabetes',
 'Pneumococcal vaccination among noninstitutionalized adults aged 18-64 years with diagnosed diabetes',
 'Pneumococcal vaccination among noninstitutionalized adults aged >= 65 years with diagnosed diabetes',
 'Foot examination among adults aged >= 18 years with diagnosed diabetes',
 'Glycosylated hemoglobin measurement among adults aged >= 18 years with diagnosed diabetes',
 'Dilated eye examination among adults aged >= 18 years with diagnosed diabetes',
 'Visits to dentist or dental clinic among adults aged >= 18 years with diagnosed diabetes',
 'Prevalence of high cholesterol among adults aged >= 18 years with diagnosed diabetes',
 'Prevalence of high blood pressure among adults aged >= 18 years with diagnosed diabetes',
 'Amputation of a lower extremity attributable to diabetes',
 'Hospitalization with diabetes as a listed diagnosis',
 'Mortality due to diabetes reported as any listed cause of death',
 'Mortality with diabetic ketoacidosis reported as any listed cause of death',
 'Prevalence of gestational diabetes',
 'Prevalence of pre-pregnancy diabetes']

In [10]:
questions = df['Question'].value_counts()

In [11]:
q_df = pd.DataFrame(questions)

In [12]:
q_df

                                                    Question
Hospitalization for heart failure among Medicar...      7488
Hospitalization for hip fracture among Medicare...      7488
Hospitalization for chronic obstructive pulmona...      7488
Hospitalization for chronic obstructive pulmona...      7488
Asthma mortality rate                                   6135
Mortality due to diabetes reported as any liste...      6135
Mortality from total cardiovascular diseases            6135
Premature mortality among adults aged 45-64 years       6135
Mortality from diseases of the heart                    6135
Mortality from coronary heart disease                   6135
Mortality with chronic obstructive pulmonary di...      6135
Mortality with end-stage renal disease                  6135
Mortality from heart failure                            6135
Mortality with chronic obstructive pulmonary di...      6135
Mortality from cerebrovascular disease (stroke)         6135
Chronic liver disease mortality                         6135
Mortality with diabetic ketoacidosis reported a...      6135
Arthritis among adults aged >= 18 years who are...      5225
Prevalence of activity limitation among adults ...      5220
Pneumococcal vaccination among noninstitutional...      5220
Obesity among adults aged >= 18 years                   5220
Recent activity limitation among adults aged >=...      5220
Dilated eye examination among adults aged >= 18...      5220
Glycosylated hemoglobin measurement among adult...      5220
Influenza vaccination among noninstitutionalize...      5220
Binge drinking frequency among adults aged >= 1...      5220
Pneumococcal vaccination among noninstitutional...      5220
Arthritis among adults aged >= 18 years                 5220
Physical inactivity among adults aged >= 18 yea...      5220
Pneumococcal vaccination among noninstitutional...      5220
...                                                      ...
Overweight or obesity among high school students         110
Local authority to regulate alcohol outlet density       110
Proportion of the population protected by a com...       110
Computer use among high school students                  110
Obesity among high school students                       110
Median daily frequency of fruit consumption amo...       110
Census tracts with healthier food retailers wit...       110
Commercial host (dram shop) liability laws               110
Live births occurring at Baby Friendly Facilities        110
Presence of regulations pertaining to screen ti...       108
State child care regulation supports onsite bre...       108
Presence of regulations pertaining to serving f...       108
Presence of regulations pertaining to serving v...       108
Farmers markets that accept Supplemental Nutrit...        55
Alcohol use before pregnancy                              55
Prevalence of pre-pregnancy diabetes                      55
Folic acid supplementation                                55
Pre-pregnancy hypertension                                55
Health insurance coverage before pregnancy                55
Poverty among women aged 18-44 years                      55
Postpartum checkup                                        55
Farmers markets that accept Women and Infant Ch...        55
Postpartum depressive symptoms                            55
Cigarette smoking before pregnancy                        55
Number of farmers markets per 100,000 residents           55
Preventive dental care before pregnancy                   55
Presence of regulations pertaining to avoiding ...        54
Prevalence of gestational diabetes                        52
Life expectancy at age 65 years                           52
Life expectancy at birth                                  52

[203 rows x 1 columns]

In [17]:
new_df = df[df['Question'] == 'Mortality due to diabetes reported as any listed cause of death']

In [19]:
new_df.head()

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,Question,Response,DataValueUnit,DataValueType,...,LocationID,TopicID,QuestionID,DataValueTypeID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2,StratificationCategoryID3,StratificationID3
292677,2014,2014,AK,Alaska,NVSS,Diabetes,Mortality due to diabetes reported as any list...,,"cases per 100,000",Age-adjusted Rate,...,2,DIA,DIA1_1,AGEADJRATE,RACE,AIAN,,,,
292678,2014,2014,AK,Alaska,NVSS,Diabetes,Mortality due to diabetes reported as any list...,,"cases per 100,000",Age-adjusted Rate,...,2,DIA,DIA1_1,AGEADJRATE,RACE,API,,,,
292679,2014,2014,AK,Alaska,NVSS,Diabetes,Mortality due to diabetes reported as any list...,,"cases per 100,000",Age-adjusted Rate,...,2,DIA,DIA1_1,AGEADJRATE,RACE,BLK,,,,
292680,2014,2014,AK,Alaska,NVSS,Diabetes,Mortality due to diabetes reported as any list...,,"cases per 100,000",Age-adjusted Rate,...,2,DIA,DIA1_1,AGEADJRATE,GENDER,GENF,,,,
292681,2014,2014,AK,Alaska,NVSS,Diabetes,Mortality due to diabetes reported as any list...,,"cases per 100,000",Age-adjusted Rate,...,2,DIA,DIA1_1,AGEADJRATE,RACE,HIS,,,,

In [50]:
alaska_2014 = new_df[(new_df['YearStart'] == 2014) & (new_df['LocationDesc'] == 'Alaska')]

In [60]:
alaska_2014.shape

(24, 34)

In [66]:
alaska_2014['Stratification1'].nunique()

8

In [64]:
alaska_2014[['DataValueType', 'DataValue', 'StratificationCategoryID1', 'Stratification1']]

,DataValueType,DataValue,StratificationCategoryID1,Stratification1
292677,Age-adjusted Rate,59.8,RACE,American Indian or Alaska Native
292678,Age-adjusted Rate,85.1,RACE,Asian or Pacific Islander
292679,Age-adjusted Rate,,RACE,"Black, non-Hispanic"
292680,Age-adjusted Rate,48.6,GENDER,Female
292681,Age-adjusted Rate,,RACE,Hispanic
292682,Age-adjusted Rate,70.4,GENDER,Male
292683,Age-adjusted Rate,59.3,OVERALL,Overall
292684,Age-adjusted Rate,54.4,RACE,"White, non-Hispanic"
293087,Crude Rate,36.8,RACE,American Indian or Alaska Native
293088,Crude Rate,51.1,RACE,Asian or Pacific Islander
293089,Crude Rate,,RACE,"Black, non-Hispanic"
293090,Crude Rate,38.6,GENDER,Female
293091,Crude Rate,,RACE,Hispanic
293092,Crude Rate,51.3,GENDER,Male
293093,Crude Rate,45.3,OVERALL,Overall
293094,Crude Rate,46.1,RACE,"White, non-Hispanic"
293501,Number,43,RACE,American Indian or Alaska Native
293502,Number,29,RACE,Asian or Pacific Islander
293503,Number,,RACE,"Black, non-Hispanic"
293504,Number,126,GENDER,Female
293505,Number,,RACE,Hispanic
293506,Number,185,GENDER,Male
293507,Number,311,OVERALL,Overall
293508,Number,221,RACE,"White, non-Hispanic"

In [68]:
# keep only age adjusted values
alaska_2014[alaska_2014['DataValueType'] == 'Age-adjusted Rate'].shape

(8, 34)

In [59]:
alaska_2014.nunique()

YearStart                     1
YearEnd                       1
LocationAbbr                  1
LocationDesc                  1
DataSource                    1
Topic                         1
Question                      1
Response                      1
DataValueUnit                 1
DataValueType                 3
DataValue                    19
DataValueAlt                 18
DataValueFootnoteSymbol       2
DatavalueFootnote             2
LowConfidenceLimit           12
HighConfidenceLimit          12
StratificationCategory1       3
Stratification1               8
StratificationCategory2       1
Stratification2               1
StratificationCategory3       1
Stratification3               1
GeoLocation                   1
ResponseID                    1
LocationID                    1
TopicID                       1
QuestionID                    1
DataValueTypeID               3
StratificationCategoryID1     3
StratificationID1             8
StratificationCategoryID2     1
StratificationID2             1
StratificationCategoryID3     1
StratificationID3             1
dtype: int64

In [37]:
new_df[['DataValueUnit', 'DataValueType', 'DataValue', 'DataValueAlt']]

            DataValueUnit      DataValueType DataValue  DataValueAlt
292677  cases per 100,000  Age-adjusted Rate      59.8          59.8
292678  cases per 100,000  Age-adjusted Rate      85.1          85.1
292679  cases per 100,000  Age-adjusted Rate                     NaN
292680  cases per 100,000  Age-adjusted Rate      48.6          48.6
292681  cases per 100,000  Age-adjusted Rate                     NaN
292682  cases per 100,000  Age-adjusted Rate      70.4          70.4
292683  cases per 100,000  Age-adjusted Rate      59.3          59.3
292684  cases per 100,000  Age-adjusted Rate      54.4          54.4
292685  cases per 100,000  Age-adjusted Rate                     NaN
292686  cases per 100,000  Age-adjusted Rate                     NaN
292687  cases per 100,000  Age-adjusted Rate      96.5          96.5
292688  cases per 100,000  Age-adjusted Rate      49.8          49.8
292689  cases per 100,000  Age-adjusted Rate        26          26.0
292690  cases per 100,000  Age-adjusted Rate      72.1          72.1
292691  cases per 100,000  Age-adjusted Rate      59.5          59.5
292692  cases per 100,000  Age-adjusted Rate      50.7          50.7
292693  cases per 100,000  Age-adjusted Rate                     NaN
292694  cases per 100,000  Age-adjusted Rate                     NaN
292695  cases per 100,000  Age-adjusted Rate     115.1         115.1
292696  cases per 100,000  Age-adjusted Rate      57.5          57.5
292697  cases per 100,000  Age-adjusted Rate      34.9          34.9
292698  cases per 100,000  Age-adjusted Rate      88.6          88.6
292699  cases per 100,000  Age-adjusted Rate      71.6          71.6
292700  cases per 100,000  Age-adjusted Rate      66.1          66.1
292701  cases per 100,000  Age-adjusted Rate     163.2         163.2
292702  cases per 100,000  Age-adjusted Rate      52.2          52.2
292703  cases per 100,000  Age-adjusted Rate      91.7          91.7
292704  cases per 100,000  Age-adjusted Rate      41.6          41.6
292705  cases per 100,000  Age-adjusted Rate      95.8          95.8
292706  cases per 100,000  Age-adjusted Rate      70.7          70.7
...                   ...                ...       ...           ...
443012                NaN             Number       198         198.0
443013                NaN             Number      2364        2364.0
443014                NaN             Number       192         192.0
443015                NaN             Number      2635        2635.0
443016                NaN             Number      4999        4999.0
443017                NaN             Number      4494        4494.0
443018                NaN             Number        69          69.0
443019                NaN             Number        26          26.0
443020                NaN             Number       294         294.0
443021                NaN             Number      2099        2099.0
443022                NaN             Number        62          62.0
443023                NaN             Number      2282        2282.0
443024                NaN             Number      4381        4381.0
443025                NaN             Number      3992        3992.0
443026                NaN             Number                     NaN
443027                NaN             Number                     NaN
443028                NaN             Number       102         102.0
443029                NaN             Number      1322        1322.0
443030                NaN             Number                     NaN
443031                NaN             Number      1252        1252.0
443032                NaN             Number      2574        2574.0
443033                NaN             Number      2465        2465.0
443034                NaN             Number                     NaN
443035                NaN             Number                     NaN
443036                NaN             Number                     NaN
443037                NaN             Number       147         147.0
443038                NaN             Number        25          25.0
443039                NaN             Number       177         177.0
443040                NaN             Number       324         324.0
443041                NaN             Number       306         306.0

[6135 rows x 4 columns]

In [45]:
new_df['Stratification1'].unique()

array(['American Indian or Alaska Native', 'Asian or Pacific Islander',
       'Black, non-Hispanic', 'Female', 'Hispanic', 'Male', 'Overall',
       'White, non-Hispanic'], dtype=object)

In [34]:
new_df.nunique()

YearStart                       5
YearEnd                         5
LocationAbbr                   52
LocationDesc                   52
DataSource                      1
Topic                           1
Question                        1
Response                        1
DataValueUnit                   1
DataValueType                   3
DataValue                    2333
DataValueAlt                 2332
DataValueFootnoteSymbol         2
DatavalueFootnote               2
LowConfidenceLimit           1123
HighConfidenceLimit          1260
StratificationCategory1         3
Stratification1                 8
StratificationCategory2         1
Stratification2                 1
StratificationCategory3         1
Stratification3                 1
GeoLocation                    51
ResponseID                      1
LocationID                     52
TopicID                         1
QuestionID                      1
DataValueTypeID                 3
StratificationCategoryID1       3
StratificationID1               8
StratificationCategoryID2       1
StratificationID2               1
StratificationCategoryID3       1
StratificationID3               1
dtype: int64

In [10]:
# extra stuff

In [ ]:
# import the original CDC dataset (large file)
df = pd.read_csv('data/U.S._Chronic_Disease_Indicators__CDI_.csv')

# save main dataset to multiple files
for topic,group_df in df.groupby(pd.Grouper(key='Topic')):
    name = f'data/{topic.lower()}.csv'
    group_df.to_csv(name)